### ISSUE TITLE
Small differences between mouse and keyboard controls 

### ISSUE THREAD

**Issue by vindowvipre** [TerryCavanagh/super-hexagon-neo-issues#1]
Two things:

In the menu, keyboard controls work fine, but mouse controls are weird. Left clicking will enter the current level, while right clicking will move to the level on the right, as you'd expect. I don't know if that is intended or not, but it certainly feels weird not being able to move left in the menus.  

The next bug has to do when you press both directional keys at the same time while playing a level. On keyboard, left will always take priority, no matter what. On mouse, whichever button you press second will take priority -- which is AWESOME. I love this change, since the old version of SH was super broken when you pressed both mouse clicks at the same time. I guess my recommendation is, if you updated keyboard controls to change directions properly, that would be much appreciated. 

Overall, I love this update, and it is great to see one of my favorite games getting some attention again. Looking forward to part 2!

**Comment by flibitijibibo** [comment]
I believe most of the game logic uses action sets including menu so there's probably a way to override directions globally to match what you're saying... and you're right, the latest should take priority.

Mouse is really weird right now: Left is action and right is menu cycle, which makes sense when you happen to know but I need to implement touch controls anyhow, so mouse will likely be folded into that for part 2.

**Comment by flibitijibibo** [comment]
With the latest Steam update the keyboard/controller input should now match the mouse's button prioritization!

The mouse menu logic for now is `WONTFIX` but expect this to change when touch controls get added in part 2.

**Comment by TerryCavanagh** [comment]
Oh, thanks for that Ethan!
