### ISSUE TITLE
No sound on iOS

### ISSUE THREAD

**Issue by proailurus** [TerryCavanagh/super-hexagon-neo-issues#18]
There is no sound on iOS 17.
phone model is 15PM

**Comment by TerryCavanagh** [comment]
Thanks for the heads up, I'll investigate. 

What device/Os version do you have? I can't replicate this on my iPad Pro running 17.3.1.

**Comment by proailurus** [comment]
I just found out that I have sound if silent mode is disabled.

What does ringtone volume have to do with media volume though? Only some apps show this behavior, it’s not consistent.

Is this some sort of iOS guideline I‘m not aware of?

**Comment by danoli3** [comment]
Yo! Yes this was implemented with Silent Mode requirement from Apple for Games when the last update was released. This is actually controlled by Apple's own internal mechanisms.

> Currently, the Ring/Silent switch will mute incoming calls, messages, and notification sounds, as well as sounds for games. This means if you have the switch engaged to Silent, only audio from videos, music, or alarms will be heard

This is completely bypassed when in silent mode if you have headphones connected though! 

Ideally user should be prompted in someway device is in silent mode

**Comment by proailurus** [comment]
I see, thanks.

I'll close it as it's an iOS quirk.
