### ISSUE TITLE
Game can stop responding when quit on Windows if a controller got reconnected

### ISSUE THREAD

**Issue by Frixuu** [TerryCavanagh/super-hexagon-neo-issues#2]
I have my wired Xbox 360 controller connected at all times to my Windows 10 PC, even if I'm not actively using it. Sometime during a play session, I've unplugged the controller and plugged it back in to the same USB port. Then, when I wanted to exit the game,

- the window stopped responding,
- both Task Manager and Process Explorer could not kill the process (access denied).

The game window stays open until Windows gets bored (for a few minutes), **but can be closed instantly if the offending controller gets disconnected.**

**Comment by flibitijibibo** [comment]
That actually sounds like it could be the HID... which means it could be rooted in SDL. Let me see what the best path is for testing this and get back to you, could be as simple as getting a stack trace, could also be something we can reproduce with an SDL test.

**Comment by flibitijibibo** [comment]
Pushed an update that I _think_ fixes this? If the latest stops this from happening this issue can be closed!
