### ISSUE TITLE
Some characters for display names are shown as controller icons in leaderboards

### ISSUE THREAD

**Issue by cnrm** [TerryCavanagh/super-hexagon-neo-issues#4]
The new fonts added for controllers seem to cause side effects when names are fetched for the leaderboards.

![1652556962](https://user-images.githubusercontent.com/5803611/168478280-9466a11a-e4b5-4f55-9291-11ece248ca59.png)

**Comment by flibitijibibo** [comment]
Looks like there are some special characters used that we recycle for prompts - I should probably replace those with '?' in the general case anyhow, will look at this for the next batch of fixes.

**Comment by flibitijibibo** [comment]
This should be fixed in the latest update, unless FreeType decides to troll us... how it works now is that we check each character against the font, and any unrecognized character gets replaced with `?`.
