### ISSUE TITLE
All audio jittery after Neo update

### ISSUE THREAD

**Issue by TheMagicJesus** [TerryCavanagh/super-hexagon-neo-issues#6]
Probably a result of my usage of a virtual audio cable. Have encountered this issue in the past

**Comment by flibitijibibo** [comment]
If disabling VAC fixes it I would try and report an issue to them, but if not I would file an SDL issue if at all possible: https://github.com/libsdl-org/SDL

Bonus points if you're able to compile the audio test...

https://github.com/libsdl-org/SDL/tree/main/VisualC

... but a full description of the setup should be enough for the SDL Windows maintainers to reproduce.

**Comment by TheMagicJesus** [comment]
Damn that was quick.Thanks! Disabling Voicemeeter/Virtual Audio Cable works but I'm always hesitant on that end.
Launch argument works like a charm while virtual audio cable is enabled

**Comment by TheMagicJesus** [comment]
Wargroove ,another game I've had this issue with, also uses SDL so I will certainly be submitting an issue on their repo as suggested
