### ISSUE TITLE
Setting description for arcade mode is showing under sound volume now

### ISSUE THREAD

**Issue by AkaFletch** [TerryCavanagh/super-hexagon-neo-issues#7]
Playing on build: 8836967
OS: Arch Linux 5.18.0

Since adding the new option to the settings menu, the description for the arcade mode shows up under sound volume
![2022-05-30-174144_1726x1080_scrot](https://user-images.githubusercontent.com/18452201/171033504-4f24d852-aa55-491b-b835-941ddc5b3f01.png)

**Comment by flibitijibibo** [comment]
Oof, not sure how I missed that - will fix this now.

**Comment by flibitijibibo** [comment]
Fix is live now!

**Comment by AkaFletch** [comment]
Fixes are far too fast over here :+1:
