### ISSUE TITLE
Somebody on steam is claiming that a previous version on linux supported 120fps mode, which is very mysterious

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/super-hexagon-neo-issues#9]
As far as I know it's always been locked to 60? Mobile versions support 120hz but the PC version hadn't been updated with that. Is this person just mistaken?

![image](https://user-images.githubusercontent.com/2874150/171193449-ee92da1b-7464-4b3e-8772-5a40e5ee50bc.png)

![image](https://user-images.githubusercontent.com/2874150/171193393-19133986-df78-4836-988b-07c50eacee14.png)

**Comment by flibitijibibo** [comment]
It definitely pushed more frames but the frames were useless - it would render without actually updating anything, so it would just waste cycles and boost fps counters. Plus, event polling was _much_ worse in the old version, it would poll once and then sleep, render a bunch, and only once updating started again would events get polled again. All that combined with a non-HFR display, I have no idea where this is coming from...

**Comment by TerryCavanagh** [comment]
Yeah! I guess they might have somehow gotten the screen to output twice as many frames, but those frames would have been useless duplicates since the logic was tied to 60fps. I think this person is probably just filling in the missing frames in their head 😅
